### ISSUE TITLE
Widget Still Doesn't Update If Not In Focus

### ISSUE THREAD

**Issue by daylightFGC** [MarcoPNS/Spotify-Stream-Widget#25]
What the title says. I'm on the latest version (1.4.0.3) and it still doesn't update correctly.

**Comment by MarcoPNS** [comment]
Hi! Thanks for your Feedback. Could you upload your log file?

**Comment by daylightFGC** [comment]
2020/06/07 14:57:18 Call 0 [DEBUG] Application started - v1.4.0.3
2020/06/07 14:57:18 Call 0 [EXCEPTION] VersionCheck_DoWork() Exception: System.InvalidCastException: Conversion from string "1.4.0.3" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at Spotify_Stream_Widget.Settings.VersionCheck_DoWork(Object sender, DoWorkEventArgs e)

**Comment by daylightFGC** [comment]
[2020-06-07.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/4742215/2020-06-07.log)

**Comment by MarcoPNS** [comment]
Except of the failed VersionCheck everything seems to be normal. 

I have already streamed an hour today with the widget and couldn't reproduce the error with the latest version. Are you minimizing the widget?

**Comment by MarcoPNS** [comment]
Does the widget display everything normally when you switch the dark mode? Maybe I can use the ApplyLightning() function to fix the problem.

**Comment by daylightFGC** [comment]
Yes I am minimising the widget and that is what's causing the issue. I thought that's what the issue was all about - you had to have the window active and not minimise it for it to display correctly?

**Comment by MarcoPNS** [comment]
Windows blocks the update of the form when minimized. In this case it keeps only the last state of the form. I will check if there is anything I can do, but actually it should not be minimized. You should have a similar problem with all minimized applications that you try to display in your streaming software.

**Comment by daylightFGC** [comment]
Ahhhh okay. My apologies. Feel free to close this issue. Thanks for your help. :)

**Comment by MarcoPNS** [comment]
I will let this issue open. In the next update the app will force that the viewer stays open.

**Comment by daylightFGC** [comment]
Ahh okay that would be great!
