### ISSUE TITLE
Intermittent authentication issue? 

### ISSUE THREAD

**Issue by TheNeonNights** [MarcoPNS/Spotify-Stream-Widget#59]
I keep getting an error which causes disconnection that I'm trying to track down.   This is what appears in the logs when it fails and throws an error.  Any ideas what the problem might be?

2021/11/06 07:18:51 Call 39331 [EXCEPTION] GetPlayback() Exception: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at SpotifyAPI.Web.SpotifyWebClient.DownloadJson[T](String url, Dictionary`2 headers)
   at SpotifyAPI.Web.SpotifyWebAPI.DownloadDataAlt[T](String url)
   at SpotifyAPI.Web.SpotifyWebAPI.DownloadData[T](String url)
   at Spotify_Stream_Widget.Viewer.VB$StateMachine_43_UpdateTrack.MoveNext()

**Comment by MarcoPNS** [comment]
I know it's been a while, but do you know what song this happened on?
